// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  help: create.doc("help", {"faq.mdx": () => import("../content/help/faq.mdx?collection=help"), "index.mdx": () => import("../content/help/index.mdx?collection=help"), "account/deleting-your-account.mdx": () => import("../content/help/account/deleting-your-account.mdx?collection=help"), "account/notification-settings.mdx": () => import("../content/help/account/notification-settings.mdx?collection=help"), "billing/payment-methods.mdx": () => import("../content/help/billing/payment-methods.mdx?collection=help"), "billing/subscriptions-and-plans.mdx": () => import("../content/help/billing/subscriptions-and-plans.mdx?collection=help"), "calendars-and-rsvps/calendar-sync.mdx": () => import("../content/help/calendars-and-rsvps/calendar-sync.mdx?collection=help"), "calendars-and-rsvps/how-rsvp-works.mdx": () => import("../content/help/calendars-and-rsvps/how-rsvp-works.mdx?collection=help"), "calendars-and-rsvps/notifications.mdx": () => import("../content/help/calendars-and-rsvps/notifications.mdx?collection=help"), "getting-started/creating-a-calendar.mdx": () => import("../content/help/getting-started/creating-a-calendar.mdx?collection=help"), "getting-started/inviting-people.mdx": () => import("../content/help/getting-started/inviting-people.mdx?collection=help"), "getting-started/understanding-the-dashboard.mdx": () => import("../content/help/getting-started/understanding-the-dashboard.mdx?collection=help"), "hosting/creating-a-plan.mdx": () => import("../content/help/hosting/creating-a-plan.mdx?collection=help"), "hosting/editing-or-canceling-a-plan.mdx": () => import("../content/help/hosting/editing-or-canceling-a-plan.mdx?collection=help"), "hosting/managing-rsvps.mdx": () => import("../content/help/hosting/managing-rsvps.mdx?collection=help"), "hosting/plan-chat.mdx": () => import("../content/help/hosting/plan-chat.mdx?collection=help"), "organizations/adding-and-removing-members.mdx": () => import("../content/help/organizations/adding-and-removing-members.mdx?collection=help"), "organizations/roles-and-permissions.mdx": () => import("../content/help/organizations/roles-and-permissions.mdx?collection=help"), "organizations/what-is-an-organization.mdx": () => import("../content/help/organizations/what-is-an-organization.mdx?collection=help"), }),
};
export default browserCollections;